### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by warcheat-mwam** [dikisiswanto/barka#1]
Maaf saya mau tanya ini untuk tema bagaimana cara installnya ya?

pas saya upload kok tidak bisa, dan muncul notif 

![image](https://user-images.githubusercontent.com/71243890/116344105-e0894380-a80f-11eb-9b2a-ca5bdf49b03c.png)

**Comment by dikisiswanto** [comment]
Pastikan nama file nya barka.zip

**Comment by warcheat-mwam** [comment]
oke baik terima kasih,
sudah bisa saya install
